version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default

  file:
    class: logging.FileHandler
    filename: logs/app.log
    level: INFO
    formatter: default

root:
  level: INFO
  handlers: [console, file]
